In [14]:
%reset
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import itertools
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import tree
from sklearn import svm
from sklearn import neighbors
from sklearn.neighbors import KNeighborsClassifier
import io 
import requests
from sklearn.metrics import classification_report, confusion_matrix


Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [15]:
#ds_ = pd.read_csv('F8N4P.csv', sep=';', na_values="?", decimal=',')# se carga el cojunto de datos csv
ds_ = pd.read_csv('F4P17.csv', sep=';', na_values="?", decimal=',')# se carga el cojunto de datos csv

#ds_ = pd.read_csv('F4NP17.csv', sep=';', na_values="?", decimal=',')
ds = ds_.dropna() # se elimina las filas/columnas con valores null
# Convertir datos categoricos a numericos
ds = ds.rename(columns = {ds.columns.values[21]:'C'}) # renombramos la ultima columna por "C" de clase
#le = preprocessing.LabelEncoder() # Label encoder de sci-kit

# Convertir datos categoricos a numericos
tipos = ds.columns[0:21].to_series().groupby(ds.dtypes).groups
ctext = tipos[np.dtype('object')]

for c in ctext:
     ds[c], _ = pd.factorize(ds[c])  

#ds = ds.apply(le.fit_transform) # Convertimos los valores de object a numericos
#ds.head() # se verifica el resultado de cargue de los dato
##VAL = pd.read_csv('VAL.csv', sep=';', na_values="?", decimal=',')
##tipos = VAL.columns[0:23].to_series().groupby(VAL.dtypes).groups
##ctext = tipos[np.dtype('object')]

##for c in ctext:
  ##   VAL[c], _ = pd.factorize(VAL[c])  

ds.C.value_counts()
ds.head()


TVE  COVM  COVP  EDUM  EDUP  MTRAB  PTRAB  #PCONV  PHERMANO  TPOBLACION  \
0    0     0     0     0     0      0      0       9         0           0   
1    1     1     0     1     1      1      0       3         3           0   
2    1     1     0     2     0      0      0       5         3           0   
3    0     1     0     2     2      0      0       4         1           0   
4    0     1     1     1     1      1      0       2         4           0   

  ...  ET  LAPTOP  INTERNET  DEPOR  RSENTI  P1-16  P2-16  P3-16   P4   C  
0 ...   0       0         0      0       0    2.9    3.4    3.4  3.6   A  
1 ...   0       0         1      1       0    2.6    2.4    2.8  3.9   A  
2 ...   0       1         1      0       1    3.1    3.4    3.5  3.9   A  
3 ...   0       1         1      0       1    3.0    3.1    3.5  3.7   A  
4 ...   0       0         0      0       1    2.7    2.9    2.1  3.1  BS  

[5 rows x 22 columns]

In [62]:

del ds['COVP']
del ds['EDUM']
del ds['LAPTOP']


In [16]:
import numpy as np
import pandas as pd
from sklearn import tree
from sklearn.model_selection import cross_val_score

import numpy as np

from sklearn.model_selection import train_test_split
x=ds.drop('C', axis = 1)
y=ds['C']
from collections import Counter
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state=1)
df=pd.DataFrame(x_train)
df['C']=y_train
dt=pd.DataFrame(x_test)
dt['C']=y_test
print('Conteo de clases conjunto train {}'.format(Counter(y_train)))
print('Conteo de Clases conjunto test  {}'.format(Counter(y_test)))


Conteo de clases conjunto train Counter({'BS': 60, 'B': 54, 'A': 40})
Conteo de Clases conjunto test  Counter({'BS': 29, 'A': 19, 'B': 19})


In [17]:
########################################################################
########################### RBF SVM  C=10.0############################
xntrain =df.drop('C', axis = 1)
yntrain = df['C']
xntest =dt.drop('C', axis = 1)
yntest = dt['C']

SVMrbf = svm.SVC(kernel='linear',C=10, gamma=10)
SVMrbf.fit(xntrain, yntrain)
#print(SVMrbf.predict(VAL))
SVMrbf_predict = SVMrbf.predict(xntest)

print("\n############## Accuracy SVM Lineal C=10, gamma=10 ##################")
print(metrics.accuracy_score(yntest, SVMrbf_predict))
print("\n############## Confusion SVM Lineal C=10, gamma=10 ################")
print(metrics.confusion_matrix(yntest, SVMrbf_predict))
print("\n############## Metricas SVM Lineal C=10, gamma=10 ##################")
print(classification_report(yntest,SVMrbf_predict))


############## Accuracy SVM Lineal C=10, gamma=10 ##################
0.8805970149253731

############## Confusion SVM Lineal C=10, gamma=10 ################
[[17  0  2]
 [ 0 17  2]
 [ 3  1 25]]

############## Metricas SVM Lineal C=10, gamma=10 ##################
              precision    recall  f1-score   support

           A       0.85      0.89      0.87        19
           B       0.94      0.89      0.92        19
          BS       0.86      0.86      0.86        29

   micro avg       0.88      0.88      0.88        67
   macro avg       0.89      0.88      0.88        67
weighted avg       0.88      0.88      0.88        67



In [7]:
SVMrbf.fit

<bound method BaseLibSVM.fit of SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=10, kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)>

In [18]:
################################################################
##################  K-Vecinos más cercanos #####################
################################################################
xntrain =df.drop('C', axis = 1)
yntrain = df['C']
xntest =dt.drop('C', axis = 1)
yntest = dt['C']

n_neighbors = 4
KNN = KNeighborsClassifier(n_neighbors)
KNN.fit(xntrain, yntrain)
KNN_predict = KNN.predict(xntest)

print("\n############## Accuracy KNN  K=4 ####################################")
print(metrics.accuracy_score(yntest, KNN_predict))
print("\n############## Confusion KNN  K=4 #####################################")
print(metrics.confusion_matrix(yntest, KNN_predict))
print("\n############## Metricas KNN  K=4 #####################################")
print(classification_report(yntest,KNN_predict))


############## Accuracy KNN  K=4 ####################################
0.5522388059701493

############## Confusion KNN  K=4 #####################################
[[ 9  1  9]
 [ 1 13  5]
 [ 2 12 15]]

############## Metricas KNN  K=4 #####################################
              precision    recall  f1-score   support

           A       0.75      0.47      0.58        19
           B       0.50      0.68      0.58        19
          BS       0.52      0.52      0.52        29

   micro avg       0.55      0.55      0.55        67
   macro avg       0.59      0.56      0.56        67
weighted avg       0.58      0.55      0.55        67



In [20]:
xntrain =df.drop('C', axis = 1)
yntrain = df['C']
xntest =dt.drop('C', axis = 1)
yntest = dt['C']
from sklearn.neural_network import MLPClassifier


clf =clf = MLPClassifier(hidden_layer_sizes=(13,13,13,13,13,13,13,13,13,13) ,activation='relu',random_state=1, learning_rate_init=0.0016)

clf.fit(x_train, y_train)

clf_predict = clf.predict(x_test)

print("\n### Accuracy MLP capas ocultas 10 ,unidades ocultas 13 ######################")
print(metrics.accuracy_score(y_test, clf_predict))
print("\n### Confusion MLP capas ocultas 10 ,unidades ocultas 13 #####################")
print(metrics.confusion_matrix(y_test, clf_predict))
print("\n### Metricas MLP capas ocultas 10 ,unidades ocultas 13 #######################")
print(classification_report(y_test, clf_predict))

ValueError: could not convert string to float: 'BS'

## "Balanceo de Datos usando Oversampling"
mejora la prediccion despues de este proceso pero hay que ajustarlo para que mejore con el categoria 1 

In [49]:
ds_ = pd.read_csv('F8N4P.csv', sep=';', na_values="?", decimal=',')# se carga el cojunto de datos csv
ds = ds_.dropna() # se elimina las filas/columnas con valores null
# Convertir datos categoricos a numericos
ds = ds.rename(columns = {ds.columns.values[22]:'C'}) # renombramos la ultima columna por "C" de clase
#le = preprocessing.LabelEncoder() # Label encoder de sci-kit

# Convertir datos categoricos a numericos
tipos = ds.columns[0:21].to_series().groupby(ds.dtypes).groups
ctext = tipos[np.dtype('object')]

for c in ctext:
     ds[c], _ = pd.factorize(ds[c])  

#ds = ds.apply(le.fit_transform) # Convertimos los valores de object a numericos
#ds.head() # se verifica el resultado de cargue de los dato

ds.C.value_counts()


BS    89
B     73
A     59
Name: C, dtype: int64

In [50]:

del ds['COVP']
del ds['EDUM']
del ds['LAPTOP']


In [51]:
from sklearn.utils import resample
# separar las clases entre mayoritaria y minoritaria 
ds_majority = ds[ds.C == "BS"]
ds_minority1 = ds[ds.C == "B"]
ds_minority2 = ds[ds.C == "A"] 
# sobre muestrear las clases minoritarias
ds_minority_upsampled1 = resample(ds_minority1, 
                                 replace=True,     # Muestreo con remplazo
                                 n_samples=89,    # cantidad de muestras a igualar 
                                 random_state=123) 

ds_minority_upsampled2 = resample(ds_minority2, 
                                 replace=True,     # Muestreo con remplazo
                                 n_samples=89,    # cantidad de muestras a igualar
                                 random_state=123) 
#ds_minority_upsampled3 = resample(ds_minority3, 
 #                                replace=True,     # Muestreo con remplazo
   #                              n_samples=2713,    # cantidad de muestras a igualar
  #                               random_state=123) 

# concaternar la clase mayoritaria con la clases minoritarias creadas recientemente
ds_upsampled = pd.concat([ds_majority, ds_minority_upsampled1,ds_minority_upsampled2])
 
# imprimir el numero de muestras por clase
ds_upsampled.C.value_counts()

A     89
BS    89
B     89
Name: C, dtype: int64

In [52]:
ds=ds_upsampled

In [53]:
import numpy as np
import pandas as pd
from sklearn import tree
from sklearn.model_selection import cross_val_score

import numpy as np

from sklearn.model_selection import train_test_split
x=ds.drop('C', axis = 1)
y=ds['C']
from collections import Counter
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state=1)
df=pd.DataFrame(x_train)
df['C']=y_train
dt=pd.DataFrame(x_test)
dt['C']=y_test
print('Conteo de clases conjunto train {}'.format(Counter(y_train)))
print('Conteo de Clases conjunto test  {}'.format(Counter(y_test)))

Conteo de clases conjunto train Counter({'A': 63, 'B': 62, 'BS': 61})
Conteo de Clases conjunto test  Counter({'BS': 28, 'B': 27, 'A': 26})


In [54]:
########################################################################
########################### RBF SVM  C=10.0############################
xntrain =df.drop('C', axis = 1)
yntrain = df['C']
xntest =dt.drop('C', axis = 1)
yntest = dt['C']

SVMrbf = svm.SVC(kernel='linear',C=10, gamma=10)
SVMrbf.fit(xntrain, yntrain)

SVMrbf_predict = SVMrbf.predict(xntest)

print("\n############## Accuracy SVM Lineal C=10, gamma=10 ##################")
print(metrics.accuracy_score(yntest, SVMrbf_predict))
print("\n############## Confusion SVM Lineal C=10, gamma=10 ################")
print(metrics.confusion_matrix(yntest, SVMrbf_predict))
print("\n############## Metricas SVM Lineal C=10, gamma=10 ##################")
print(classification_report(yntest,SVMrbf_predict))


############## Accuracy SVM Lineal C=10, gamma=10 ##################
0.8888888888888888

############## Confusion SVM Lineal C=10, gamma=10 ################
[[26  0  0]
 [ 0 25  2]
 [ 3  4 21]]

############## Metricas SVM Lineal C=10, gamma=10 ##################
              precision    recall  f1-score   support

           A       0.90      1.00      0.95        26
           B       0.86      0.93      0.89        27
          BS       0.91      0.75      0.82        28

   micro avg       0.89      0.89      0.89        81
   macro avg       0.89      0.89      0.89        81
weighted avg       0.89      0.89      0.89        81



In [55]:
################################################################
##################  K-Vecinos más cercanos #####################
################################################################
xntrain =df.drop('C', axis = 1)
yntrain = df['C']
xntest =dt.drop('C', axis = 1)
yntest = dt['C']

n_neighbors = 4
KNN = KNeighborsClassifier(n_neighbors)
KNN.fit(xntrain, yntrain)
KNN_predict = KNN.predict(xntest)

print("\n############## Accuracy KNN  K=4 ####################################")
print(metrics.accuracy_score(yntest, KNN_predict))
print("\n############## Confusion KNN  K=4 #####################################")
print(metrics.confusion_matrix(yntest, KNN_predict))
print("\n############## Metricas KNN  K=4 #####################################")
print(classification_report(yntest,KNN_predict))


############## Accuracy KNN  K=4 ####################################
0.4567901234567901

############## Confusion KNN  K=4 #####################################
[[16  2  8]
 [ 3 13 11]
 [ 8 12  8]]

############## Metricas KNN  K=4 #####################################
              precision    recall  f1-score   support

           A       0.59      0.62      0.60        26
           B       0.48      0.48      0.48        27
          BS       0.30      0.29      0.29        28

   micro avg       0.46      0.46      0.46        81
   macro avg       0.46      0.46      0.46        81
weighted avg       0.45      0.46      0.45        81



In [56]:
xntrain =df.drop('C', axis = 1)
yntrain = df['C']
xntest =dt.drop('C', axis = 1)
yntest = dt['C']

from sklearn.neural_network import MLPClassifier


clf = MLPClassifier(hidden_layer_sizes=(64,64,64,64,64,64,64,64,64,64), activation='relu',
                    random_state=1, learning_rate_init=0.00016)

clf.fit(xntrain, yntrain)

clf_predict2 = clf.predict(xntest)

print("\n############## Accuracy MLP layer hidden 10 ,unidades 64 #########")
print(metrics.accuracy_score(yntest, clf_predict2))
print("\n############## Confusion MLP layer hidden 10 ,unidades 64 #########")
print(metrics.confusion_matrix(yntest, clf_predict2))
print("\n############## Metricas MLP layer hidden 10 ,unidades 64 ##########")
print(classification_report(yntest,clf_predict2))


############## Accuracy MLP layer hidden 10 ,unidades 64 #########
0.8024691358024691

############## Confusion MLP layer hidden 10 ,unidades 64 #########
[[25  0  1]
 [ 0 23  4]
 [ 3  8 17]]

############## Metricas MLP layer hidden 10 ,unidades 64 ##########
              precision    recall  f1-score   support

           A       0.89      0.96      0.93        26
           B       0.74      0.85      0.79        27
          BS       0.77      0.61      0.68        28

   micro avg       0.80      0.80      0.80        81
   macro avg       0.80      0.81      0.80        81
weighted avg       0.80      0.80      0.80        81



C:\Users\Andres\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


# "Balanceo de Datos usando undersampling"

In [63]:
ds_ = pd.read_csv('F8N4P.csv', sep=';', na_values="?", decimal=',')# se carga el cojunto de datos csv
ds = ds_.dropna() # se elimina las filas/columnas con valores null
# Convertir datos categoricos a numericos
ds = ds.rename(columns = {ds.columns.values[22]:'C'}) # renombramos la ultima columna por "C" de clase
#le = preprocessing.LabelEncoder() # Label encoder de sci-kit

# Convertir datos categoricos a numericos
tipos = ds.columns[0:21].to_series().groupby(ds.dtypes).groups
ctext = tipos[np.dtype('object')]

for c in ctext:
     ds[c], _ = pd.factorize(ds[c])  

#ds = ds.apply(le.fit_transform) # Convertimos los valores de object a numericos
#ds.head() # se verifica el resultado de cargue de los dato

ds.C.value_counts()


BS    89
B     73
A     59
Name: C, dtype: int64

In [64]:

del ds['COVP']
del ds['EDUM']
del ds['LAPTOP']


In [65]:
from sklearn.utils import resample
# separar las clases entre mayoritaria y minoritaria 
ds_majority = ds[ds.C == "BS"]
ds_minorityd1 = ds[ds.C == "B"]
ds_minorityd2 = ds[ds.C == "A"] 
#ds_minorityd3 = ds[ds.C == 3]
# sobre muestrear las clases minoritarias
ds_majority_downsampled = resample(ds_majority, 
                                 replace=False,     # Muestreo sin remplaso
                                 n_samples=59,    # cantidad de muestra a igualar
                                 random_state=123) 

ds_majority_downsampled1 = resample(ds_minorityd1, 
                                 replace=False,     # Muestreo sin remplaso
                                 n_samples=59,    # cantidad de muestra a igualar
                                 random_state=123) 



# concaternar la clase mayoritaria con la clases minoritarias creadas recientemente
ds_downsampled = pd.concat([ds_majority_downsampled,ds_majority_downsampled1, ds_minorityd2 ])
 
# imprimir el numero de muestras por clase
ds_downsampled.C.value_counts()

A     59
BS    59
B     59
Name: C, dtype: int64

In [66]:
ds=ds_downsampled

In [67]:
import numpy as np
import pandas as pd
from sklearn import tree
from sklearn.model_selection import cross_val_score

import numpy as np

from sklearn.model_selection import train_test_split
x=ds.drop('C', axis = 1)
y=ds['C']
from collections import Counter
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state=1)
df=pd.DataFrame(x_train)
df['C']=y_train
dt=pd.DataFrame(x_test)
dt['C']=y_test
print('Conteo de clases conjunto train {}'.format(Counter(y_train)))
print('Conteo de Clases conjunto test  {}'.format(Counter(y_test)))

Conteo de clases conjunto train Counter({'A': 48, 'B': 39, 'BS': 36})
Conteo de Clases conjunto test  Counter({'BS': 23, 'B': 20, 'A': 11})


In [71]:
########################################################################
########################### RBF SVM  C=10.0############################
xntrain =df.drop('C', axis = 1)
yntrain = df['C']
xntest =dt.drop('C', axis = 1)
yntest = dt['C']

SVMrbf = svm.SVC(kernel='linear',C=10, gamma=10)
SVMrbf.fit(xntrain, yntrain)

SVMrbf_predict = SVMrbf.predict(xntest)

print("\n############## Accuracy SVM Lineal C=10, gamma=10 ##################")
print(metrics.accuracy_score(yntest, SVMrbf_predict))
print("\n############## Confusion SVM Lineal C=10, gamma=10 ################")
print(metrics.confusion_matrix(yntest, SVMrbf_predict))
print("\n############## Metricas SVM Lineal C=10, gamma=10 ##################")
print(classification_report(yntest,SVMrbf_predict))


############## Accuracy SVM Lineal C=10, gamma=10 ##################
0.7407407407407407

############## Confusion SVM Lineal C=10, gamma=10 ################
[[ 9  0  2]
 [ 1 14  5]
 [ 4  2 17]]

############## Metricas SVM Lineal C=10, gamma=10 ##################
              precision    recall  f1-score   support

           A       0.64      0.82      0.72        11
           B       0.88      0.70      0.78        20
          BS       0.71      0.74      0.72        23

   micro avg       0.74      0.74      0.74        54
   macro avg       0.74      0.75      0.74        54
weighted avg       0.76      0.74      0.74        54



In [69]:
################################################################
##################  K-Vecinos más cercanos #####################
################################################################
xntrain =df.drop('C', axis = 1)
yntrain = df['C']
xntest =dt.drop('C', axis = 1)
yntest = dt['C']

n_neighbors = 4
KNN = KNeighborsClassifier(n_neighbors)
KNN.fit(xntrain, yntrain)
KNN_predict = KNN.predict(xntest)

print("\n############## Accuracy KNN  K=4 ####################################")
print(metrics.accuracy_score(yntest, KNN_predict))
print("\n############## Confusion KNN  K=4 #####################################")
print(metrics.confusion_matrix(yntest, KNN_predict))
print("\n############## Metricas KNN  K=4 #####################################")
print(classification_report(yntest,KNN_predict))


############## Accuracy KNN  K=4 ####################################
0.4074074074074074

############## Confusion KNN  K=4 #####################################
[[ 9  1  1]
 [ 5 11  4]
 [ 9 12  2]]

############## Metricas KNN  K=4 #####################################
              precision    recall  f1-score   support

           A       0.39      0.82      0.53        11
           B       0.46      0.55      0.50        20
          BS       0.29      0.09      0.13        23

   micro avg       0.41      0.41      0.41        54
   macro avg       0.38      0.49      0.39        54
weighted avg       0.37      0.41      0.35        54



In [70]:
xntrain =df.drop('C', axis = 1)
yntrain = df['C']
xntest =dt.drop('C', axis = 1)
yntest = dt['C']

from sklearn.neural_network import MLPClassifier


clf = MLPClassifier(hidden_layer_sizes=(64,64,64,64,64,64,64,64,64,64), activation='relu',
                    random_state=1, learning_rate_init=0.00016)

clf.fit(xntrain, yntrain)

clf_predict2 = clf.predict(xntest)

print("\n############## Accuracy MLP layer hidden 10 ,unidades 64 #########")
print(metrics.accuracy_score(yntest, clf_predict2))
print("\n############## Confusion MLP layer hidden 10 ,unidades 64 #########")
print(metrics.confusion_matrix(yntest, clf_predict2))
print("\n############## Metricas MLP layer hidden 10 ,unidades 64 ##########")
print(classification_report(yntest,clf_predict2))


############## Accuracy MLP layer hidden 10 ,unidades 64 #########
0.6296296296296297

############## Confusion MLP layer hidden 10 ,unidades 64 #########
[[ 7  1  3]
 [ 3 12  5]
 [ 5  3 15]]

############## Metricas MLP layer hidden 10 ,unidades 64 ##########
              precision    recall  f1-score   support

           A       0.47      0.64      0.54        11
           B       0.75      0.60      0.67        20
          BS       0.65      0.65      0.65        23

   micro avg       0.63      0.63      0.63        54
   macro avg       0.62      0.63      0.62        54
weighted avg       0.65      0.63      0.63        54



C:\Users\Andres\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [95]:
#ds_ = pd.read_csv('F8N4P.csv', sep=';', na_values="?", decimal=',')# se carga el cojunto de datos csv
ds_ = pd.read_csv('417.csv', sep=';', na_values="?", decimal=',')# se carga el cojunto de datos csv

#ds_ = pd.read_csv('F4NP17.csv', sep=';', na_values="?", decimal=',')
ds = ds_.dropna() # se elimina las filas/columnas con valores null
# Convertir datos categoricos a numericos
ds = ds.rename(columns = {ds.columns.values[21]:'C'}) # renombramos la ultima columna por "C" de clase
#le = preprocessing.LabelEncoder() # Label encoder de sci-kit

# Convertir datos categoricos a numericos
tipos = ds.columns[0:21].to_series().groupby(ds.dtypes).groups
ctext = tipos[np.dtype('object')]

for c in ctext:
     ds[c], _ = pd.factorize(ds[c])  



##for c in ctext:
  ##   VAL[c], _ = pd.factorize(VAL[c])  

ds.C.value_counts()
ds.head()

TVE  COVM  COVP  EDUM  EDUP  MTRAB  PTRAB  #PCONV  PHERMANO  TPOBLACION  \
0    0     0     0     0     0      0      0       9         0           0   
1    1     1     0     1     1      1      0       3         3           0   
2    1     1     0     2     0      0      0       5         3           0   
3    0     1     0     2     2      0      0       4         1           0   
4    0     1     1     1     1      1      0       2         4           0   

  ...  ET  LAPTOP  INTERNET  DEPOR  RSENTI  P1-16  P2-16  P3-16  P4-16   C  
0 ...   0       0         0      0       0    2.9    3.4    3.4    3.5  BS  
1 ...   0       0         1      1       0    2.6    2.4    2.8    3.2  BS  
2 ...   0       1         1      0       1    3.1    3.4    3.5    3.4  BS  
3 ...   0       1         1      0       1    3.0    3.1    3.5    3.7  BS  
4 ...   0       0         0      0       1    2.7    2.9    2.1    2.0  BS  

[5 rows x 22 columns]

In [136]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
#from sklearn.cross_validation import cross_val_score, cross_val_predict
from sklearn import linear_model
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import KFold
import pandas as pd
from sklearn import metrics

# Load the boston dataset
#data = datasets.load_boston()
data.data=ds.drop('C', axis = 1)
data.target=ds['C']
# extract the predictors and target data.
df = pd.DataFrame(data.data)
y =  pd.DataFrame(data.target)

In [137]:
kf = KFold(n_splits = 10, shuffle = True)
#rf_reg = RandomForestRegressor()

SVM = svm.SVC(kernel='linear',C=10, gamma=10)


In [138]:
scores = []
for i in range(10):
    result = next(kf.split(df), None)
    x_train = df.iloc[result[0]]
    x_test = df.iloc[result[1]]
    y_train = y.iloc[result[0]]
    y_test = y.iloc[result[1]]
    model = SVM.fit(x_train,y_train)
    predictions = SVM.predict(x_test)
    scores.append(model.score(x_test,y_test))
print('Scores from each Iteration: ', scores)
print('Average K-Fold Score :' , np.mean(scores))

C:\Users\Andres\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Andres\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Andres\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Andres\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,

Scores from each Iteration:  [0.4782608695652174, 0.34782608695652173, 0.5652173913043478, 0.6086956521739131, 0.5217391304347826, 0.6956521739130435, 0.5217391304347826, 0.6086956521739131, 0.5652173913043478, 0.5652173913043478]
Average K-Fold Score : 0.5478260869565217


C:\Users\Andres\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Andres\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Andres\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [139]:
print("\n############## Accuracy SVM Lineal C=10, gamma=10 ##################")
print(metrics.accuracy_score(y_test, predictions))
print("\n############## Confusion SVM Lineal C=10, gamma=10 ################")
print(metrics.confusion_matrix(y_test, predictions))
print("\n############## Metricas SVM Lineal C=10, gamma=10 ##################")
print(classification_report(y_test,predictions))


############## Accuracy SVM Lineal C=10, gamma=10 ##################
0.5652173913043478

############## Confusion SVM Lineal C=10, gamma=10 ################
[[1 0 0]
 [0 6 5]
 [2 3 6]]

############## Metricas SVM Lineal C=10, gamma=10 ##################
              precision    recall  f1-score   support

           A       0.33      1.00      0.50         1
           B       0.67      0.55      0.60        11
          BS       0.55      0.55      0.55        11

   micro avg       0.57      0.57      0.57        23
   macro avg       0.52      0.70      0.55        23
weighted avg       0.59      0.57      0.57        23



In [140]:
# Load the boston dataset
#data = datasets.load_boston()
data.data=ds.drop('C', axis = 1)
data.target=ds['C']
# extract the predictors and target data.
#df = pd.DataFrame(data.data)
#y =  pd.DataFrame(data.target)
 
# extract the predictors and target data.
predictors = data.data
target = data.target

In [141]:
predictors.shape, target.shape

((221, 21), (221,))

In [142]:
x_train,x_test,y_train,y_test = train_test_split(predictors,target,test_size = 0.2)

In [143]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((176, 21), (45, 21), (176,), (45,))

In [144]:
SVM = svm.SVC(kernel='linear',C=10, gamma=10)
model = SVM.fit(x_train,y_train)
#rf_reg = RandomForestRegressor()
#rf_reg.fit(x_train,y_train)

In [145]:
#y_pred = rf_reg.predict(x_test)
predictions = SVM.predict(x_test)

In [147]:
rsqure_score = model.score(x_train,y_train)
print('R^2: {}'.format(rsqure_score))

R^2: 0.7272727272727273


In [153]:
cv_r2_scores_rf = cross_val_score(model, predictors, target, cv=5,scoring='r2')
print(cv_r2_scores_rf)
print("Mean 5-Fold R Squared: {}".format(np.mean(cv_r2_scores_rf)))

ValueError: could not convert string to float: 'BS'